<?php

namespace Solidarity\Backend\Action;

use Doctrine\ORM\EntityManagerInterface;
use Laminas\Config\Config;
use League\Plates\Engine;
use Psr\Log\LoggerInterface as Logger;
use Skeletor\Core\Action\Web\Html;
use Solidarity\Transaction\Entity\Transaction;

/**
 * Expire payment instructions the donor never acted on.
 *
 * An instruction is created with STATUS_NEW and the donor is told they have 72 hours.
 * Past that, the money it reserves has to go back into circulation: NEW counts as
 * "allocated" (TransactionRepository::getAllocatedStatuses), so until the status moves
 * it keeps consuming the donor's pledged budget, the beneficiary's remaining need for
 * the period, and the donor's per-person yearly cap. Neither of the two statuses below
 * is allocated, so a single status change frees all three.
 *
 * Which status depends on whether the donor ever came back after we generated it:
 *
 *   - never logged in since createdAt -> STATUS_NOT_PAID. They never saw the
 *     instruction, so there is nothing to chase.
 *   - logged in but never confirmed  -> STATUS_EXPIRED. They saw it and may still pay
 *     late, so the record stays reconcilable by hand in the dashboard.
 *
 * ORDER MATTERS: run this immediately before createTransactions, so the budget it frees
 * is reallocated in the same cycle. The 72h window must be strictly shorter than the gap
 * between two createTransactions runs, or an instruction generated by the previous run is
 * still a few minutes short of 72h when this looks at it and survives a whole extra cycle
 * (Mon 07:00 -> Thu 06:xx is 71h5xm). With Mon/Thu that means Thursday's pair must run at
 * least an hour later than Monday's.
 *
 * Run: php public/cli.php expireInstructions run
 * Preview without writing: php public/cli.php expireInstructions dry
 */
class ExpireInstructions extends Html
{
    /** Matches the 72h the donor is promised in the instructions dialog. */
    private const EXPIRE_AFTER = '-72 hours';

    /** Rows per query — keeps the identity map from growing without bound. */
    private const BATCH_SIZE = 100;

    private const COMMENT_EXPIRED = 'Instrukcija za uplatu je automatski prebačena u ovaj status pošto je prošlo više od 72 sata.';
    private const COMMENT_NOT_PAID = 'Instrukcija za uplatu je automatski prebačena u ovaj status pošto donator nije pristupio sajtu od trenutka kreiranja instrukcije.';

    public function __construct(
        Logger $logger,
        Config $config,
        Engine $template,
        private EntityManagerInterface $em,
    ) {
        parent::__construct($logger, $config, $template);
    }

    public function __invoke(
        \Psr\Http\Message\ServerRequestInterface $request,
        \Psr\Http\Message\ResponseInterface $response
    ) {
        // CliSkeletor passes the argv tail as the "params" attribute.
        $params = (array) $request->getAttribute('params', []);
        $dry = in_array('dry', $params, true);

        $cutoff = new \DateTimeImmutable(self::EXPIRE_AFTER);
        $expired = 0;
        $notPaid = 0;
        $lastId = 0;

        $this->getLogger()->log(
            \Monolog\Level::Info,
            sprintf(
                'expireInstructions %s: expiring NEW instructions created before %s',
                $dry ? 'DRY-RUN' : 'RUN',
                $cutoff->format('Y-m-d H:i:s')
            )
        );

        // Cursor on id rather than re-running the same query: in dry-run nothing changes
        // status, so a status-only query would return the same rows forever.
        while ($batch = $this->fetchBatch($cutoff, $lastId)) {
            foreach ($batch as $transaction) {
                $lastId = $transaction->id;

                if ($this->donorSawIt($transaction)) {
                    $status = Transaction::STATUS_EXPIRED;
                    $comment = self::COMMENT_EXPIRED;
                    $expired++;
                } else {
                    $status = Transaction::STATUS_NOT_PAID;
                    $comment = self::COMMENT_NOT_PAID;
                    $notPaid++;
                }

                $this->getLogger()->log(\Monolog\Level::Info, sprintf(
                    'Transaction %d (%s, %d RSD, created %s) -> %s',
                    $transaction->id,
                    $transaction->getReferenceCode(),
                    $transaction->amount,
                    $transaction->getCreatedAt()->format('Y-m-d H:i:s'),
                    Transaction::getHrStatus($status)
                ));

                if ($dry) {
                    continue;
                }

                $transaction->status = $status;
                // Appended, not replaced: an instruction can already carry an operator note.
                $transaction->comment = trim(($transaction->comment ? $transaction->comment . ' ' : '') . $comment);
            }

            if (!$dry) {
                $this->em->flush();
            }
            $this->em->clear();
        }

        $summary = sprintf(
            'expireInstructions %s finished: %d expired, %d not paid, %d total.',
            $dry ? 'DRY-RUN' : 'RUN',
            $expired,
            $notPaid,
            $expired + $notPaid
        );
        $this->getLogger()->log(\Monolog\Level::Info, $summary);
        echo $summary . PHP_EOL;

        return $response;
    }

    /**
     * Did the donor load any page after this instruction was generated?
     *
     * Uses lastVisit, not lastLogin: sessions last 30 days and the instructions email
     * carries no magic-link token, so a donor can read an instruction repeatedly without
     * ever re-authenticating. Keying off lastLogin would file those as NOT_PAID ("never
     * saw it") when they plainly did. A missing donor (detached by GDPR erasure) counts
     * as "no" — there is nobody left to have seen it.
     */
    private function donorSawIt(Transaction $transaction): bool
    {
        $donor = $transaction->donor;
        if (!$donor || !$donor->lastVisit) {
            return false;
        }

        return $donor->lastVisit > $transaction->getCreatedAt();
    }

    /**
     * @return Transaction[]
     */
    private function fetchBatch(\DateTimeImmutable $cutoff, int $lastId): array
    {
        return $this->em->createQueryBuilder()
            ->select('t')
            ->from(Transaction::class, 't')
            // Only NEW: WAITING_CONFIRMATION means the donor already reported paying,
            // and expiring that would throw away a real payment.
            ->where('t.status = :status')
            ->andWhere('t.createdAt < :cutoff')
            ->andWhere('t.id > :lastId')
            ->setParameter('status', Transaction::STATUS_NEW)
            ->setParameter('cutoff', $cutoff)
            ->setParameter('lastId', $lastId)
            ->orderBy('t.id', 'ASC')
            ->setMaxResults(self::BATCH_SIZE)
            ->getQuery()
            ->getResult();
    }
}
